spring:
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 30
  rabbitmq:
    host: rabbitmq
#    host: ${RABBITMQ_SERVER_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    virtual-host: /
#    username: test
#    password: password

  data:
    mongodb:
      uri: mongodb://mongo:27017
      database: ${MONGODB_DATABASE:msa_test}

axon:
  amqp:
    exchange: product.events.fanout.exchange
    transaction-mode: none
    durable-messages: true

eureka:
  client:
    service-url:
      default-zone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

external:
  amqp:
    exchange:
      fanout:
        auto-delete: false
    bind:
      route-key: "*"
    queue: product.default.queue

  event-sourcing:
        events-collection-name: service-events
        snapshot-collection-name: service-events-snapshots
  heroku:
    rabbitmq-env-var: rabbitmq
