eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    exchange: product.events.fanout.exchange
    queue: event.stream
    terminal: product.axon.terminal

  rabbitmq:
    hostname: localhost
    username: test
    password: password

  data:
    rest:
      #base-path:api/v1

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframwork: INFO
    app: DEBUG
